name: "Push OAS to github"
description: "Push OAS to github"
inputs:
  PAT:
    description: 'A Github key'
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.PAT }}
          ref: ${{ github.head_ref }}

      - name: Check branch name
        shell: bash
        run: |
          if ! echo "${{ github.head_ref }}" | egrep '^((feature|bugfix|hotfix)/MOB-[0-9]*(\(\.*\))*|release/[\.0-9]*)$' ; 
          then 
          exit 1
          fi
          
      - name: Push branch name if needed to github
        shell: bash
        run: |          
          echo "${{ github.head_ref }}" > /tmp/branch.txt
          if ! cmp -s "/tmp/branch.txt" ".github/tmp/branch.txt" ; then
          cp /tmp/branch.txt .github/tmp/branch.txt
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git fetch
          git pull
          git add .github/tmp/branch.txt
          git commit -m "Update BranchReference from GitHub Actions"
          git push origin "${{ github.head_ref }}"
          exit 1
          fi
