name: Auto-Merge Release to Main

on:
  push:
    branches:
      - release/*  # Trigger the workflow on pushes to the release branch

jobs:
  merge-release-to-main:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to allow merging

      # Step 2: Set up Git configuration
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Merge release into main
      - name: Merge Release into Main
        run: |
          # Fetch all branches
          git fetch origin
          
          # Checkout main branch
          git checkout main
          
          # Merge release into main
          git merge release --no-ff -m "Auto-merge release into main [skip ci]"

      # Step 4: Push changes to main
      - name: Push to Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
